### ISSUE TITLE
Setting "Max squares in same category" is not enforced

### ISSUE THREAD

**Issue by ShaneD20** [awsker/EldenBingo#19]
[category.json](https://github.com/user-attachments/files/16629297/category.json)
![BingoCategoryTest](https://github.com/user-attachments/assets/970930a4-7468-43ba-b326-4c48c0a6a67b)

As was testing out categories per the readme and it seems there is no enforced limit per category.

- I was testing a limit of 4 from a file (attached) with 7 categories
- The attached image is the result with the "cats" category populating 7 times
- version 0.13.1

**Comment by schwutz** [comment]
Is contribution by anyone allowed/wanted? If so, can anyone elaborate on the expected behavior for this, so I can provde a fix? I ask for elaboration, because there is some code being executed when at least one category exceeds the limit.

**Comment by awsker** [comment]
Hey. Thanks for reporting this. I will admit I haven't done rigorous testing with the category limit, so it's not unthinkable that something slipped through the cracks.

@schwutz Your understanding of the expected behaviour and the point of my solution is correct. I'm working on a new version so I will look into this before release. Anyone is welcome to submit a pull request for a fix they've implemented.

**Comment by awsker** [comment]
Fixed. When I added multiple categories for a square, the "continue" that was supposed to skip to the next square instead continued an inner foreach loop. Thanks for reporting.

**Comment by schwutz** [comment]
> Your understanding of the expected behaviour and the point of my solution is correct. I'm working on a new version so I will look into this before release. Anyone is welcome to submit a pull request for a fix they've implemented.

good to know 👍🏻 next time i'll issue a PR, if needed :)
